// The hex cartogram: 435 equal-area districts.
//
// Layout is generated by engine/dashboard/geo.py from Census centroids under the
// 118th Congress, because no public layout matches the 2020 apportionment -- the
// well-known one is wrong for thirteen states.
//
// Shading defaults to a value-suppressing uncertainty palette: certain districts
// get fine gradations, uncertain ones collapse toward neutral. That is deliberate.
// Most House districts have no usable poll, and a map that renders them as
// confidently as the polled ones is lying by omission. How many of each is a
// number the coverage readout draws from the payload; written down here it would
// only date the file.
import d3 from '../d3.js';
import { C, svg, vsupScale, diverging, fmtMargin, hoverable, legendSwatch } from './util.js';

const MODES = {
  prob:   { label: 'Win probability', domain: 1,
            get: r => (r.win_prob == null ? null : r.win_prob * 2 - 1),
            fmt: r => (r.ind_slot || r.three_way
              ? `independent win ${(indWin(r) * 100).toFixed(0)}% · D win ${(dWin(r) * 100).toFixed(0)}%`
              : `D win ${(r.win_prob * 100).toFixed(0)}%`) },
  margin: { label: 'Median margin', domain: 30,
            get: r => r.median_margin,
            fmt: r => `median ${fmtMargin(r.median_margin)}` },
  swing:  { label: 'Swing vs 2024', domain: 12,
            get: r => (r.median_margin == null || r.lean == null ? null : r.median_margin - r.lean),
            fmt: r => (r.median_margin == null ? '—'
                       : `${(r.median_margin - r.lean >= 0 ? '+' : '')}${(r.median_margin - r.lean).toFixed(1)} vs 2024 lean`) },
};

// An independent standing in a missing party's slot. `win_prob` is the frame's D
// slot, so where that slot IS the independent their chance is win_prob and a
// Democrat's is zero; where they oppose the D slot, their chance is the loss.
// A seat they are favoured in takes the caveat colour on every mode: the D-to-R
// scale cannot say "neither", and shading Osborn's Nebraska blue said Democrat.
const indWin = r => (r.three_way ? (r.ind_win_prob || 0)
  : r.ind_slot === 'D' ? r.win_prob : 1 - r.win_prob);
const dWin = r => (r.ind_slot === 'D' ? 0 : r.win_prob);

// Both layouts share these, so the two map modes cannot drift apart in what
// they encode -- only in where they put it.
function paint(M, vsup, showUncertainty) {
  return d => {
    const r = d.race;
    if (r.locked) return r.locked_party === 'D' ? C.demDeep : C.repDeep;
    if ((r.ind_slot || r.three_way) && r.win_prob != null && indWin(r) >= 0.5) return C.accent;
    const v = M.get(r);
    return showUncertainty ? vsup(v, r.sigma_total)
                           : diverging(Math.max(-1, Math.min(1, v / M.domain)));
  };
}

function describe(M) {
  return d => {
    const r = d.race;
    return `<b>${r.race_id}</b> · ${r.state}<br>` +
      (r.locked ? 'settled — same-party general'
                : `${M.fmt(r)}<br><span class="tip-dim">±${r.sigma_total?.toFixed(1)} pts · ` +
                  `${r.n_polls ? `${r.n_polls} poll${r.n_polls > 1 ? 's' : ''}` : 'prior only'}` +
                  `${r.boundary_stale ? ' · shape is the 2024 line' : ''}</span>` +
                  (r.ind_slot === 'D' ? '<br><span class="tip-dim">no Democrat on the ballot: the '
                    + 'margin is the independent\u2019s, whose win counts for neither party</span>'
                   : r.ind_slot ? '<br><span class="tip-dim">no Republican on the ballot: the '
                    + 'independent\u2019s win counts for neither party</span>' : ''));
  };
}

function legend(host, staleCount) {
  const key = document.createElement('div');
  key.className = 'keys';
  key.append(
    legendSwatch('Democratic', C.dem),
    legendSwatch('Republican', C.rep),
    legendSwatch('Independent favoured', C.accent, 'counts for neither party'),
    legendSwatch('Uncertain', d3.interpolateLab(C.mid, C.surface)(0.42),
                 'colour is suppressed where the model knows less'),
    legendSwatch('2024 boundaries', C.dim, `${staleCount} districts redrawn for 2026; the forecast is on the new lines, this shape is not`, true),
  );
  host.append(key);
}

function staleHatch(s) {
  const defs = s.append('defs');
  // Texture, not shade. At 4px/0.55 this washed California and Texas to grey and
  // did the suppressing that the palette is supposed to do, twice over.
  defs.append('pattern').attr('id', 'stale').attr('width', 5).attr('height', 5)
    .attr('patternUnits', 'userSpaceOnUse').attr('patternTransform', 'rotate(45)')
    .append('line').attr('x1', 0).attr('y1', 0).attr('x2', 0).attr('y2', 5)
    .attr('stroke', C.bg).attr('stroke-width', 1).attr('stroke-opacity', 0.3);
}

// Real district boundaries. Same projection and the same encodings as the hex
// layout, so the toggle changes only WHERE a district is drawn.
export function choropleth(host, { boundaries, races, mode = 'prob', showUncertainty = true, onPick }) {
  host.replaceChildren();
  const byId = new Map(races.map(r => [r.race_id, r]));
  const D = Object.entries(boundaries.districts)
    .map(([race_id, d]) => ({ race_id, d, race: byId.get(race_id) }))
    .filter(x => x.race);

  const M = MODES[mode];
  const vsup = vsupScale({ domain: M.domain });
  // The projection is fixed, so the extent is too; measured once off the paths.
  const nums = [];
  for (const x of D) for (const m of x.d.matchAll(/(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/g)) {
    nums.push([+m[1], +m[2]]);
  }
  const xs = nums.map(p => p[0]), ys = nums.map(p => p[1]);
  const pad = 8;
  const minX = Math.min(...xs) - pad, minY = Math.min(...ys) - pad;
  const W = Math.max(...xs) - minX + pad, H = Math.max(...ys) - minY + pad;

  const s = svg(host, W, H, `District map shaded by ${M.label.toLowerCase()}`);
  staleHatch(s);
  const g = s.append('g').attr('transform', `translate(${-minX},${-minY})`);

  const cells = g.selectAll('path.cd').data(D).join('path').attr('class', 'cd')
    .attr('d', x => x.d)
    .attr('fill', paint(M, vsup, showUncertainty))
    .attr('stroke', C.bg).attr('stroke-width', 0.4)
    .style('cursor', 'pointer')
    .on('click', (e, x) => onPick && onPick(x.race));

  g.selectAll('path.stale').data(D.filter(x => x.race.boundary_stale)).join('path')
    .attr('class', 'stale').attr('d', x => x.d)
    .attr('fill', 'url(#stale)').attr('pointer-events', 'none');

  hoverable(cells, describe(M));
  legend(host, D.filter(x => x.race.boundary_stale).length);
  return { byId, cells };
}

function hexPath(cx, cy, s) {
  const p = [];
  for (let k = 0; k < 6; k++) {
    p.push([cx + s * Math.sin(Math.PI / 3 * k), cy - s * Math.cos(Math.PI / 3 * k)]);
  }
  return 'M' + p.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join(' L') + 'Z';
}

export function cartogram(host, { geo, races, mode = 'prob', showUncertainty = true, onPick }) {
  host.replaceChildren();
  const byId = new Map(races.map(r => [r.race_id, r]));
  const D = Object.entries(geo.districts)
    .map(([race_id, h]) => ({ race_id, ...h, race: byId.get(race_id) }))
    .filter(d => d.race);

  const size = geo.hex.size;
  const xs = D.map(d => d.x), ys = D.map(d => d.y);
  const minX = Math.min(...xs), minY = Math.min(...ys);
  const W = Math.max(...xs) - minX + 4 * size, H = Math.max(...ys) - minY + 4 * size;

  const M = MODES[mode];
  const vsup = vsupScale({ domain: M.domain });
  const s = svg(host, W, H, `Hex cartogram of 435 districts shaded by ${M.label.toLowerCase()}`);

  staleHatch(s);
  const cells = s.selectAll('path.cd').data(D).join('path').attr('class', 'cd')
    .attr('d', d => hexPath(d.x - minX + 2 * size, d.y - minY + 2 * size, size * 0.93))
    .attr('fill', paint(M, vsup, showUncertainty))
    .attr('stroke', C.bg).attr('stroke-width', 1)
    .style('cursor', 'pointer')
    .on('click', (e, d) => onPick && onPick(d.race));

  // Districts on superseded lines get a hatch as well as suppressed colour --
  // their POSITION on this map is approximate too, not just their number.
  s.selectAll('path.stale').data(D.filter(d => d.race.boundary_stale)).join('path')
    .attr('class', 'stale')
    .attr('d', d => hexPath(d.x - minX + 2 * size, d.y - minY + 2 * size, size * 0.93))
    .attr('fill', 'url(#stale)').attr('pointer-events', 'none');

  hoverable(cells, describe(M));
  legend(host, D.filter(d => d.race.boundary_stale).length);
  return { byId, cells };
}

export const cartogramModes = MODES;

// ---- statewide maps -------------------------------------------------------
//
// The Senate and the governorships are elected statewide, so neither the
// district hexes nor the district boundaries are the right unit for them. Both
// maps below key on the STATE, and both draw all fifty -- including the ones
// with no race this cycle, greyed and labelled "not up in 2026". Only a third of
// the Senate is on any ballot, and a map that quietly showed 35 states would
// hide the single most important thing about how the chamber turns over.

// A state's race, when it has exactly one. `governor` has 36 and `senate` 35,
// and the Senate has two specials this cycle (OH-SEN-SP, FL-SEN-SP) which means
// a state CAN hold two — so this returns a list and the map says when it is
// drawing the more competitive of two.
function byState(races, chamber) {
  const m = new Map();
  for (const r of races) {
    if (r.chamber !== chamber) continue;
    if (!m.has(r.state)) m.set(r.state, []);
    m.get(r.state).push(r);
  }
  return m;
}

// Of two races in one state, the map draws the one in more doubt: a state where
// a safe seat and a coin-flip are both on the ballot is a competitive state, and
// colouring it by the safe one would say the opposite.
const leadRace = list => list.slice().sort(
  (a, b) => Math.abs(a.win_prob - 0.5) - Math.abs(b.win_prob - 0.5))[0];

// A state with no race this cycle. One resolved colour rather than a colour at
// reduced opacity: opacity applies to the fill and not the stroke, which left
// the district seams inside an unfilled state showing through as a grid.
const OFF = d3.interpolateLab(C.line, C.bg)(0.45);

// ...and a texture on top of it, because "not up this cycle" and "too uncertain
// to colour" would otherwise both be grey. Nevada, which has a governor race the
// model barely knows, was all but indistinguishable from Wisconsin, which has no
// race at all. The palette rule on this page is that hue never carries anything
// alone; this is the same rule applied to the absence of a hue.
function offHatch(s) {
  s.append('defs').append('pattern').attr('id', 'notup')
    .attr('width', 6).attr('height', 6)
    .attr('patternUnits', 'userSpaceOnUse').attr('patternTransform', 'rotate(45)')
    .append('line').attr('x1', 0).attr('y1', 0).attr('x2', 0).attr('y2', 6)
    .attr('stroke', C.faint).attr('stroke-width', 1).attr('stroke-opacity', 0.45);
}

function stateCells(geo, races, chamber) {
  const on = byState(races, chamber);
  return Object.entries(geo.states).map(([state, h]) => {
    const list = on.get(state) || [];
    return { state, ...h, list, race: list.length ? leadRace(list) : null };
  });
}

function stateDescribe(M, chamber, cycle) {
  return d => {
    if (!d.race) {
      return `<b>${d.state}</b><br><span class="tip-dim">no ${chamber} race in ${cycle}</span>`;
    }
    const r = d.race;
    return `<b>${r.race_id}</b> · ${d.state}<br>` +
      (r.locked ? 'settled — same-party general' : `${M.fmt(r)}<br>`) +
      `<span class="tip-dim">σ ${r.sigma_total?.toFixed(1)} · ` +
      `${r.n_polls ? `${r.n_polls} poll${r.n_polls > 1 ? 's' : ''}` : 'prior only'}` +
      (d.list.length > 1
        ? `<br>${d.list.length} races here — showing the closest, ${r.race_id}`
        : '') + '</span>';
  };
}

function stateLegend(host, offCount, chamber, cycle) {
  const key = document.createElement('div');
  key.className = 'keys';
  key.append(
    legendSwatch('Democratic', C.dem),
    legendSwatch('Republican', C.rep),
    legendSwatch('Independent favoured', C.accent, 'counts for neither party'),
    legendSwatch('Uncertain', d3.interpolateLab(C.mid, C.surface)(0.42),
                 'colour is suppressed where the model knows less'),
    legendSwatch(`Not up in ${cycle}`, C.faint,
                 `${offCount} states hold no ${chamber} race this cycle`, true),
  );
  host.append(key);
}

// One equal hex per state. Equal, because that is what the Senate is: a map
// that sized states by population would draw California fifty-two times the
// area of Wyoming for two seats apiece.
export function stateCartogram(host, { geo, races, chamber, cycle = 2026,
                                       mode = 'prob', showUncertainty = true, onPick }) {
  host.replaceChildren();
  const D = stateCells(geo, races, chamber);
  const size = geo.state_hex.size;
  const xs = D.map(d => d.x), ys = D.map(d => d.y);
  const minX = Math.min(...xs), minY = Math.min(...ys);
  const W = Math.max(...xs) - minX + 4 * size, H = Math.max(...ys) - minY + 4 * size;

  const M = MODES[mode];
  const vsup = vsupScale({ domain: M.domain });
  const s = svg(host, W, H,
    `Hex cartogram of the fifty states, ${chamber} races shaded by ${M.label.toLowerCase()}`);

  offHatch(s);
  const at = d => [d.x - minX + 2 * size, d.y - minY + 2 * size];
  const cells = s.selectAll('path.st').data(D).join('path').attr('class', 'st')
    .attr('d', d => hexPath(...at(d), size * 0.93))
    .attr('fill', d => (d.race ? paint(M, vsup, showUncertainty)(d) : OFF))
    .attr('stroke', C.bg).attr('stroke-width', 1.5)
    .style('cursor', d => (d.race ? 'pointer' : 'default'))
    .on('click', (e, d) => d.race && onPick && onPick(d.race));

  s.selectAll('path.off').data(D.filter(d => !d.race)).join('path').attr('class', 'off')
    .attr('d', d => hexPath(...at(d), size * 0.93))
    .attr('fill', 'url(#notup)').attr('pointer-events', 'none');

  // Two letters fit inside a 40px hex and remove the need to hover to know
  // where you are, which a hex grid otherwise demands.
  s.selectAll('text.st').data(D).join('text').attr('class', 'st')
    .attr('x', d => at(d)[0]).attr('y', d => at(d)[1] + 4)
    .attr('text-anchor', 'middle').attr('font-size', 11.5).attr('font-weight', 600)
    .attr('fill', d => (d.race ? C.bg : C.faint))
    .attr('pointer-events', 'none')
    .text(d => d.state);

  hoverable(cells, stateDescribe(M, chamber, cycle));
  stateLegend(host, D.filter(d => !d.race).length, chamber, cycle);
  return { byId: new Map(races.map(r => [r.race_id, r])), cells };
}

// Real geography for a statewide office. There is no state boundary file: a
// state IS the union of its districts, so its districts are drawn and filled
// with its race's colour, and the seams between them are stroked in that same
// colour so the state reads as one shape.
export function stateChoropleth(host, { boundaries, geo, races, chamber, cycle = 2026,
                                        mode = 'prob', showUncertainty = true, onPick }) {
  host.replaceChildren();
  const cells0 = stateCells(geo, races, chamber);
  const info = new Map(cells0.map(d => [d.state, d]));

  const D = Object.entries(boundaries.districts)
    .map(([race_id, d]) => ({ race_id, d, state: race_id.slice(0, 2) }))
    .map(x => ({ ...x, st: info.get(x.state) }))
    .filter(x => x.st)
    // `race` alongside `st` so the draw-by-draw replay can read every map the
    // same way, whichever unit it is drawn in.
    .map(x => ({ ...x, race: x.st.race }));

  const M = MODES[mode];
  const vsup = vsupScale({ domain: M.domain });
  const nums = [];
  for (const x of D) for (const m of x.d.matchAll(/(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/g)) {
    nums.push([+m[1], +m[2]]);
  }
  const xs = nums.map(p => p[0]), ys = nums.map(p => p[1]);
  const pad = 8;
  const minX = Math.min(...xs) - pad, minY = Math.min(...ys) - pad;
  const W = Math.max(...xs) - minX + pad, H = Math.max(...ys) - minY + pad;

  const s = svg(host, W, H,
    `State map, ${chamber} races shaded by ${M.label.toLowerCase()}`);
  offHatch(s);
  const g = s.append('g').attr('transform', `translate(${-minX},${-minY})`);

  const fill = x => (x.st.race ? paint(M, vsup, showUncertainty)(x.st) : OFF);
  const cells = g.selectAll('path.cd').data(D).join('path').attr('class', 'cd')
    .attr('d', x => x.d)
    .attr('fill', fill)
    // Stroked in its own fill, so the district seams inside a state close up and
    // the state reads as the single shape the office is elected across.
    .attr('stroke', fill).attr('stroke-width', 0.7)
    .style('cursor', x => (x.st.race ? 'pointer' : 'default'))
    .on('click', (e, x) => x.st.race && onPick && onPick(x.st.race));

  g.selectAll('path.off').data(D.filter(x => !x.st.race)).join('path').attr('class', 'off')
    .attr('d', x => x.d)
    .attr('fill', 'url(#notup)').attr('stroke', 'url(#notup)').attr('stroke-width', 0.7)
    .attr('pointer-events', 'none');

  hoverable(cells, x => stateDescribe(M, chamber, cycle)(x.st));
  stateLegend(host, cells0.filter(d => !d.race).length, chamber, cycle);
  return { byId: new Map(races.map(r => [r.race_id, r])), cells };
}
